name = "your-project-name"
type = "javascript"

[build]
  command = "npm run build"  # Your build command
  cwd = "src"  # The directory where your Next.js app resides

[build.upload]
  format = "service-worker"  # For Next.js with Workers environment
  pages_build_output_dir = ".next"  # The directory where your built assets will be located
  # This specifies where Cloudflare should look for the output after the build process is finished

[[env]]
name = "NODE_ENV"
value = "production"
